spring:
  application:
    name: rag-village
  jackson:
    default-property-inclusion: non_empty
    mapper:
      accept-case-insensitive-enums: true

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: llama3.1:8b
      
server:
  port: 1337