spring:
  application:
    name: rag-village
  jackson:
    default-property-inclusion: non_empty
    mapper:
      accept-case-insensitive-enums: true

langchain4j:
  ollama:
    url: http://localhost:11434
    model-name: llama3.1:8b
    temperature: 0.7
    log-requests: true
    log-responses: true
  ollama-vision:
    url: http://localhost:11434
    model-name: llava:latest
    temperature: 0.7
    log-requests: true
    log-responses: true

logging:
  level:
    dev:
      langchain4j: DEBUG

server:
  port: 1337